Repository octokit/oauth-app.js, pull requests merged in 2021-04, with the labels that each got.

#217 ci(test): `test_matrix` and `test` jobs
  .github/workflows/test.yml
Labels: maintenance

#216 feat(typescript): Inherit types from `defaults.Octokit` set via `App.defaults({ Octokit })`
  package-lock.json
  src/add-event-handler.ts
  src/emit-event.ts
  src/index.ts
  src/middleware/node/index.ts
  src/middleware/node/middleware.ts
  src/types.ts
  test/typescript-validate.ts
Labels: feature, typescript

#221 fix: remove type imports from "http" for Deno compatibility
  src/middleware/node/middleware.ts
  src/middleware/node/on-unhandled-request-default.ts
  src/middleware/node/parse-request.ts
  src/middleware/node/types.ts
Labels: bug, deno, typescript

#226 docs(README): GitHub Enterprise Server usage
  README.md
Labels: bug, documentation

#227 ci: add NodeJS v16 to test matrix
  .github/workflows/test.yml
Labels: maintenance
