Repository octokit/oauth-app.js, pull requests merged in 2021-08, with the labels that each got.

#257 Enables CORS for HTTP endpoints
  src/middleware/handle-request.ts
  test/cloudflare-handler.test.ts
  test/node-middleware.test.ts
Labels: feature

#256 Delete `authentication.clientSecret` from HTTP responses
  package-lock.json
  src/methods/check-token.ts
  src/methods/refresh-token.ts
  src/methods/reset-token.ts
  src/methods/scope-token.ts
  src/middleware/handle-request.ts
  test/app.test.ts
  test/cloudflare-handler.test.ts
  test/node-middleware.test.ts
Labels: bug

#260 Modify `getUserOctokit` example code
  README.md
Labels: bug, documentation
