Repository octokit/oauth-app.js, pull requests merged in 2023-06, with the labels that each got.

#414 ci: stop testing against NodeJS v14, v16
  .github/workflows/test.yml
  package.json
  scripts/build.mjs
Labels: Type: Maintenance, Type: Breaking change

#430 Revert "fix(deps): update dependency @octokit/oauth-authorization-url…
  package-lock.json
  package.json
Labels: Type: Maintenance

#343 v5
  .github/workflows/test.yml
  README.md
  package-lock.json
  package.json
  scripts/build.mjs
  src/index.ts
  src/middleware/README.md
  src/middleware/aws-lambda/api-gateway-v2.ts
  src/middleware/handle-request.ts
  src/middleware/node/index.ts
  src/middleware/unknown-route-response.ts
  src/middleware/web-worker/index.ts
  test/aws-lambda-api-gateway-v2.test.ts
  test/deprecations.test.ts
  test/node-middleware.test.ts
  test/smoke.test.ts
  test/web-worker-handler.test.ts
Labels: Type: Feature, Type: Breaking change
