Repository octokit/oauth-app.js, pull requests merged in 2024-02, with the labels that each got.

#503 docs: fix some spelling
  CONTRIBUTING.md
  README.md
Labels: Type: Documentation

#506 feat: package is now ESM
  README.md
  package-lock.json
  package.json
  scripts/build.mjs
  src/index.ts
  src/middleware/aws-lambda/api-gateway-v2.ts
  src/types.ts
  test/app.test.ts
  test/aws-lambda-api-gateway-v2.test.ts
  test/node-middleware.test.ts
  test/tsconfig.test.json
  test/web-worker-handler.test.ts
Labels: Type: Feature, Type: Breaking change

#508 fix(pkg): add `main` entry point
  scripts/build.mjs
Labels: Type: Bug
